
#############################
### Custom bind           ###
#############################
# start app
bind = ALT, R, exec, rofi -show drun
bind = $mainMod, B, exec, google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --disable-gpu
bind = $mainMod CTRL, B, exec, microsoft-edge-stable --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-wayland-ime --disable-gpu
bind = $mainMod CTRL, F, exec, firefox 
bind = $mainMod SHIFT, H, exec, pkill waybar || waybar &
bind = $mainMod SHIFT, P, exec, hyprpicker -a
bind = $mainMod, PERIOD, exec, gucharmap
#shell
bind = ALT, G, exec, $HOME/Application/shells/z9_pro.sh
# 选择剪切历史
bind = $mainMod SHIFT, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
# resize
bind = ALT SHIFT,R,submap,resize
submap = resize
binde=,right,resizeactive,10 0
binde=,left,resizeactive,-10 0
binde=,up,resizeactive,0 -10
binde=,down,resizeactive,0 10
binde=,escape,submap,reset
submap=reset
# lock
bind = $mainMod, L, exec, $HOME/.config/hypr/hyprlock.sh #hyprlock
bind = $mainMod, O, exec, wlogout
# window
bind = $mainMod, F, fullscreen,
bind = $mainMod CTRL, C, centerwindow
# shot
#bind = CTRL ALT, A, exec, hyprshot-gui
bind = CTRL ALT, A, exec, XDG_CURRENT_DESKTOP=sway QT_QPA_PLATFORM=wayland flameshot gui
bind = CTRL ALT, Q, exec, hyprshot -m region -s --clipboard-only # 只保存到剪切板
bind = CTRL ALT, E, exec, hyprshot -m region -r - | swappy -f - # 编辑截图

# record
bind = $mainMod SHIFT, R, exec, notify-send "start record" "recording to $HOME/Videos/record-xxxx.mp4" && wf-recorder -g "$(slurp)" -f "$HOME/Videos/record-`date +'%Y%m%d%H%M%S'`.mp4"
bind = $mainMod SHIFT, D, exec, pkill wf-recorder && notify-send "finish" "record save in $HOME/Videos/record-`date +'%Y%m%d%H%M%S'`.mp4"

# music control
bind = $mainMod ALT, LEFT, exec, playerctl previous
bind = $mainMod ALT, RIGHT, exec, playerctl next
bind = $mainMod ALT, UP, exec, playerctl volume 0.1+
bind = $mainMod ALT, DOWN, exec, playerctl volume 0.1-
bind = $mainMod ALT, P, exec, playerctl play-pause


