hwdec=auto # 硬件加速 auto（自动选择），vaapi（Intel/AMD）、nvdec（NVIDIA）、vdpau（旧 NVIDIA 显卡）
vo=gpu
gpu-context=wayland
profile=gpu-hq
scale=ewa_lanczossharp # 高质量压缩算法

# 解决屏幕撕裂
video-sync=display-resample
interpolation
tscale=oversample

# 指定默认音轨
aid=auto # 自动选择
alang=zh,zh-CN,en # 优先中文,后英文

# 截图存放位置
screenshot-directory=~/Pictures/screenshot/mpv
screenshot-format=png
screenshot-template="%F_%p"


