# 监控器配置文件
# app表示指定某些应用所需要将接收到消息写进的文件
# contains表示所有应用标题+内容体包含指定内容写进的文件
# 2026.2.7 by dralee

[app]
Feishu=$HOME/.config/hypr/scripts/dbus-monitor/Feishu.log

[contains]
@All=$HOME/.config/hypr/scripts/dbus-monitor/containsAtAll.log
